MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[34,45], [17, 23], [9, 12], [5, 6], [3, 3], [1, 1]] #[38, 19, 10, 5, 3, 1]
        STRIDES: [[8, 8], [16, 16], [30, 30] , [54, 60], [90, 120], [270, 360]]
        MIN_SIZES: [[19, 25], [41, 54], [90, 119], [138, 184], [186, 248], [235, 313]]
        MAX_SIZES: [[41, 54], [90, 119], [138, 184], [186, 248], [235, 313], [283, 378]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]

INPUT:
    IMAGE_SIZE: [270, 360] #300
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 10000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"
