MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256] #[128, 256, 128, 128, 64, 64]  #[512, 1024, 512, 256, 256, 256] 
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [38, 19, 10, 5, 3, 1] # [112, 56, 28, 14, 7, 1]  # [75, 38, 19, 10, 5, 1]
        STRIDES: [8, 16, 32, 64, 100, 300]
        MIN_SIZES: [21, 45, 99, 153, 207, 261]
        MAX_SIZES: [45, 99, 153, 207, 261, 315]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 12000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/resnet'
DATASET_DIR: "datasets"
